import test from 'node:test';import assert from 'node:assert/strict';import{normalize,defaults,posterSVG,filterPosters,escapeXML}from'../src/engine.mjs';import{posters,articles}from'../src/posters.mjs';
test('normalization bounds unsafe and unexpected inputs',()=>{const n=normalize({text1:'x'.repeat(100),text2:null,shape:'evil',layout:'wrong',palette:'bad',offset:500,angle:-90,grain:'NaN'});assert.equal(n.text1.length,22);assert.equal(n.text2,'');assert.equal(n.shape,'star');assert.equal(n.layout,'burst');assert.equal(n.palette,'acid');assert.equal(n.offset,30);assert.equal(n.angle,-15);assert.equal(n.grain,0)});
test('SVG escapes untrusted strings rather than executing markup',()=>{const svg=posterSVG({text1:'<svg onload="x">',text2:'&"</text>'});assert(!svg.includes('<svg onload'));assert(svg.includes('&lt;svg'));assert(svg.startsWith('<svg xmlns='));assert(svg.includes('width="1400" height="1960"'));assert.equal(escapeXML('<&>'), '&lt;&amp;&gt;')});
test('blank text remains a meaningful valid shape-only poster',()=>{const svg=posterSVG({text1:'',text2:'',grain:0});assert(svg.includes('Плакат без текста'));assert(svg.includes('<polygon'));assert(!svg.includes('undefined'))});
test('every shape layout and palette creates distinct well-formed SVG',()=>{const out=new Set();for(const shape of ['star','circle','eye'])for(const layout of ['burst','split','steps'])for(const palette of ['acid','pink','blue','paper']){const svg=posterSVG({shape,layout,palette});assert.equal(svg.match(/<svg\b/g).length,1);assert(svg.endsWith('</svg>'));assert(!svg.includes('NaN'));out.add(svg)}assert.equal(out.size,36)});
test('filters combine category keyword favorites and alphabetical sort',()=>{assert.equal(filterPosters(posters).length,8);assert.equal(filterPosters(posters,{category:'type'}).length,3);assert.equal(filterPosters(posters,{category:'collage'}).length,2);assert.equal(filterPosters(posters,{query:'ГРОМЧЕ'}).length,1);assert.equal(filterPosters(posters,{query:'   '}).length,8);assert.equal(filterPosters(posters,{query:'nonexistentxyz'}).length,0);assert.equal(filterPosters(posters,{savedOnly:true,saved:[]}).length,0);assert.deepEqual(filterPosters(posters,{savedOnly:true,saved:['look-again']}).map(p=>p.id),['look-again']);assert.equal(filterPosters(posters,{category:'type',savedOnly:true,saved:['look-again']}).length,0);const sorted=filterPosters(posters,{sort:'title'});assert.equal(sorted[0].name,'Без тихого режима');assert.equal(posters[0].id,'louder-than-words')});
test('unique poster and journal slugs and substantive editorial copy',()=>{assert.equal(new Set(posters.map(p=>p.id)).size,8);assert.equal(new Set(articles.map(p=>p.id)).size,3);assert(articles.every(a=>a.sections.length===4&&a.sections.every(s=>s[1].length>150)));assert(posters.every(p=>p.desc.length>100&&p.note.length>100))});

test('angle and layer offset affect every composition',()=>{for(const layout of ['burst','split','steps']){assert.notEqual(posterSVG({layout,angle:-15}),posterSVG({layout,angle:15}));assert.notEqual(posterSVG({layout,offset:0}),posterSVG({layout,offset:30}))}});
