export const palettes={acid:['#f1ff38','#141414','#f22ba8'],pink:['#ff3dac','#141414','#fff9e9'],blue:['#2545f5','#fff9e9','#f1ff38'],paper:['#fff9e9','#2545f5','#ff3dac']};
export const defaults={text1:'ДЕЛАЙ',text2:'ШУМ',palette:'acid',shape:'star',layout:'burst',offset:10,angle:-6,grain:45};
export function escapeXML(s){return String(s).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));}
export function normalize(state={}) {const n={...defaults,...state};for(const k of ['text1','text2']) n[k]=String(n[k]??'').slice(0,22);if(!palettes[n.palette])n.palette='acid';if(!['star','circle','eye'].includes(n.shape))n.shape='star';if(!['burst','split','steps'].includes(n.layout))n.layout='burst';for(const [k,min,max] of [['offset',0,30],['angle',-15,15],['grain',0,100]])n[k]=Math.max(min,Math.min(max,Number(n[k])||0));return n;}
export function filterPosters(data,{category='all',query='',savedOnly=false,saved=[],sort='edition'}={}) {const q=query.trim().toLocaleLowerCase('ru');const filtered=data.filter(p=>(category==='all'||p.category===category)&&(!savedOnly||saved.includes(p.id))&&(!q||(p.name+' '+p.categoryName+' '+p.desc).toLocaleLowerCase('ru').includes(q)));return filtered.sort(sort==='title'?(a,b)=>a.name.localeCompare(b.name,'ru'):(a,b)=>Number(a.edition)-Number(b.edition));}
function star(cx,cy,r){return Array.from({length:24},(_,i)=>{const a=i*Math.PI/12;const rr=i%2?r*.57:r;return `${cx+Math.cos(a)*rr},${cy+Math.sin(a)*rr}`}).join(' ');}
export function posterSVG(input={},customColors){const s=normalize(input),[bg,ink,accent]=customColors||palettes[s.palette],offset=s.offset;const shape=s.shape==='star'?`<polygon points="${star(700,890,460)}"/>`:s.shape==='circle'?'<circle cx="700" cy="890" r="420"/>':'<path d="M190 890Q700 230 1210 890Q700 1550 190 890Z"/><circle cx="700" cy="890" r="145" fill="'+ink+'"/>';let pattern='';for(let y=24;y<1960;y+=36)for(let x=20;x<1400;x+=36){const r=(.7+(x+y)%5/2)*s.grain/100;pattern+=`<circle cx="${x}" cy="${y}" r="${r.toFixed(1)}"/>`;}
const text=(v,y,fill,dx=0)=>`<text x="${700+dx}" y="${y}" fill="${fill}" text-anchor="middle" textLength="${v.length>1?1240:600}" lengthAdjust="spacingAndGlyphs" font-family="Arial Black,Arial,sans-serif" font-weight="900" font-size="240">${escapeXML(v||' ')}</text>`;
let content=s.layout==='split'?`<rect x="0" y="980" width="1400" height="980" fill="${ink}"/> <g fill="${accent}" transform="translate(${offset} ${offset})">${shape}</g><g fill="${bg}" transform="scale(.63) translate(410 530)">${shape}</g>${text(s.text1,310,ink)}${text(s.text2,1810,bg)}`:s.layout==='steps'?`<g fill="${ink}" transform="translate(${offset},${offset}) rotate(${s.angle},700,890)">${shape}</g><g fill="${accent}" transform="rotate(${s.angle},700,890)">${shape}</g><rect x="-100" y="300" width="1460" height="315" fill="${ink}" transform="rotate(-8 700 500)"/><rect x="70" y="1120" width="1400" height="315" fill="${ink}" transform="rotate(6 700 1300)"/>${text(s.text1,565,bg,-20)}${text(s.text2,1375,bg,20)}`:`<g fill="${ink}" transform="translate(${offset},${offset}) rotate(${s.angle},700,890)">${shape}</g><g fill="${accent}" transform="rotate(${s.angle},700,890)">${shape}</g>${text(s.text1,350,accent,offset)}${text(s.text1,340,ink)}${text(s.text2,1760,accent,offset)}${text(s.text2,1750,ink)}`;
return `<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="1960" viewBox="0 0 1400 1960" role="img" aria-label="${escapeXML((s.text1+' '+s.text2).trim()||'Плакат без текста')}"><title>${escapeXML((s.text1+' '+s.text2).trim()||'Плакат без текста')}</title><rect width="1400" height="1960" fill="${bg}"/><g transform="rotate(${s.angle*.5},700,980)">${content}</g><g fill="${ink}" opacity=".15">${pattern}</g><path d="M50 45H1350M50 1905H1350" fill="none" stroke="${s.layout==='split'?accent:ink}" stroke-width="3"/><text x="55" y="95" font-family="Arial,sans-serif" font-size="28" font-weight="700" fill="${ink}">ШУМ / ЦИФРОВОЙ ЛИСТ</text><text x="55" y="1870" font-family="Arial,sans-serif" font-size="28" font-weight="700" fill="${s.layout==='split'?bg:ink}">RISO RIOT — НЕЗАВИСИМЫЙ ПОСТЕР-КЛУБ</text><text x="1345" y="95" font-family="Arial,sans-serif" text-anchor="end" font-size="28" fill="${ink}">01 / 01</text></svg>`;
}
